### ISSUE TITLE
Specific commit and wider commit history

### ISSUE THREAD

**Issue by Lewiscowles1986** [bobbingwide/wp071#2]
I ask because it says there are 18 commits. WordPress was forked from B2-cafe press. It'd be even nicer with a full commit log if that is available somewhere. :+1: nice project though!

**Comment by bobbingwide** [comment]
Hi Lewis, this is a fork of v0.71-gold, dated 9th June 2003.
The commits are the changes I made to get it to work with PHP 7, then a few more for PHP 8.
I didn't get the version with PHP 8 to look the same as the version with PHP 7, as evidenced by the new screen capture ( screenshot-6 ), where the header and top menu from screenshot-5 is missing.

**Comment by Lewiscowles1986** [comment]
Do you think it might be a fork from [this commit](https://github.com/WordPress/WordPress/commit/0e07af22b6b846b67f156011221b67c2313e1397), or the [prior commit](https://github.com/WordPress/WordPress/commit/02fdd8cab26d3344b2466ec5b94e62f4e5ac3029)?

I know it's nerdy, but I feel like I need to get yours and replay them atop the base commit for provenance.

**Comment by Lewiscowles1986** [comment]
Going to close this out as it cleanly (cleanly enough) rebased from the wordpress git (non-github). For anyone interested, these 19 commits, sit atop 196 others, so it's incredibly early in WordPress journey and a wonderful bit of software archiving.

[0.71 tag](https://github.com/Lewiscowles1986/WordPress/tree/0.71)
Link to attempted rebase removed (looks like you did some funky stuff with git)
had another go [here](https://github.com/Lewiscowles1986/WordPress/commits/0.71-herb-changes)

I know this is cheeky, but I really would rather this included the full history. Now it's polluted saying we both authored some because I cherry-picked commits. Some commits have very little to do with WordPress on php8, or like the `magic_gpc_quotes` polyfill, could be in a central file.

I wonder if another approach might make this cleaner. In any case it's certainly held my interest.
